str="hello"
print('l' in str)
print('l' not in str)
print(str.count('l'))
print(str.index('o'))
print(str.index('l'))
lst=[10,10,20,30]
print(10 in lst)
print(50 not in lst)
print(lst.count(30))
print(lst.index(20))
tuple=("hi","hello","python","c","hi")
print("hi" in tuple)
print("hello" not in tuple)
print(tuple.count("hi"))
print(tuple.index('hi'))